version: '3.8'
services:
  redis:
    image: redis:7.0
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StronK@Passw0rd
    ports:
      - "1433:1433"
    networks:
    - mynetwork

  crud.webapi:
    image: crud-api-image
    container_name: crud-api
    build:
      context: ..\crud-api\Crud.WebApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"           # Expose WebAPI on port 5000
    depends_on:
      - redis                 # Ensure Redis starts before the WebAPI
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=YourDatabaseName;User=sa;Password=StronK@Passw0rd;Encrypt=false;TrustServerCertificate=true
      - REDIS_CONNECTION_STRING=redis:6379  # Use Redis service name as the host
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  redis_data:
